[package]
name = "example"
version = "0.1.0"
authors = ["Zachary Catlin <z@zc.is>"]
edition = "2018"
publish = false
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { path = "../webview-submodule" }
